### ISSUE TITLE
运行ResNet出现问题

### ISSUE THREAD

**Issue by lianqingsong** [adamcavendish/PaddlePaddle-ResNet-ImageClassification#1]
您好，我复制您的ResNet-ImageClassification的训练代码，想训练自己的10分类数据集，结果出现
![image](https://user-images.githubusercontent.com/41495766/49783505-f851f100-fd54-11e8-90bf-5f75ef178561.png)
这种错误，请问要怎么改呢

**Comment by lianqingsong** [comment]
![image](https://user-images.githubusercontent.com/41495766/49784396-1705b700-fd58-11e8-9a78-353b24870c57.png)
这个是什么意思呢？为什么加.transpose（（2,0,1））呢

**Comment by lianqingsong** [comment]
@adamcavendish

**Comment by adamcavendish** [comment]
你是 mnist 么？ResNet 的预训练模型只能用于彩色图像。如果是黑白的，你可以复制那个通道为三个通道来模拟彩色图像。

**Comment by lianqingsong** [comment]
类似minst，我的数据集是从试卷上印下来的手写数字。我设置读取为rbg格式，设置了三通道 @adamcavendish 
还是报这个错误。
加.transpose（（2,0,1））这个有什么用呢

**Comment by adamcavendish** [comment]
`transpose((2, 0, 1))` 是为了将原本数据格式 `(图像高度, 图像宽度, 图像通道数)` 转换为 `(图像通道数, 图像高度, 图像宽度)`

这些 API 请自行查阅文档
[transpose 文档](http://www.paddlepaddle.org/documentation/docs/en/1.2/api/layers.html#transpose)

使用这种格式的原因是因为 paddlepaddle 的层主要以这种格式为输入形式，如

[conv2d 文档](http://www.paddlepaddle.org/documentation/docs/en/1.2/api/layers.html#conv2d)

其中指出：

```
Input and Output are in NCHW format, where ...
```

**Comment by lianqingsong** [comment]
好的，非常感谢

**Comment by lianqingsong** [comment]
我在测试的时候出现这个问题
![image](https://user-images.githubusercontent.com/41495766/49867820-91ad0000-fe46-11e8-9797-6e1c9360feb8.png)
我把batch_size调成1还是报这个错误，请问这个错误错在哪了呢

**Comment by adamcavendish** [comment]
你读读里面的英文，它已经告诉你了。你 GPU 显存不够。你可以换成 CPU 来做。

**Comment by lianqingsong** [comment]
非常感谢，已经成功预测了。但有一个问题，为什么我训练的时候最后的准确率都是99%，到预测的时候准确率最高49%，最低10%呢，您认为问题出在哪了呢 @adamcavendish

**Comment by lianqingsong** [comment]
我发现最后预测的时候并没有使用我已经训练好的模型，请问您是怎么使用你自己训练好的模型呢，在代码里没有找到加载自己的模型呀 @adamcavendish

**Comment by adamcavendish** [comment]
预测与训练的准确率这里是 off topic 的，可能的原因有很多，过拟合、数据分布不同、预处理条件等等。加载自己的模型和加载官方模型无差别。
